# Generated by Django 5.2.5 on 2025-08-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor', models.CharField(blank=True, null=True, verbose_name='Corredor')),
                ('prateleira', models.IntegerField(blank=True, null=True, verbose_name='Prateleira')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('categoria', models.IntegerField(blank=True, choices=[(0, 'Bebida'), (1, 'Comida'), (2, 'Outros')], null=True)),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('codigo_identificador', models.IntegerField(blank=True, null=True, verbose_name='Código Indentificador')),
                ('valor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estoque', to='armazem.localizacao', verbose_name='Localizacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estoque', to='armazem.produto')),
            ],
        ),
    ]
