# Generated by Django 5.2.5 on 2025-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='ultima_movimentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de movimentacao'),
        ),
    ]
