# Generated by Django 5.2.5 on 2025-08-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0002_estoque_ultima_movimentacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['produto__nome']},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'ordering': ['corredor']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='estoque',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estoque_localizacao', to='armazem.localizacao', verbose_name='Localizacao'),
        ),
    ]
