# Generated by Django 5.2.5 on 2025-08-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0003_alter_estoque_options_alter_localizacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_localizacao', to='armazem.localizacao', verbose_name='Localizacao'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='armazem.produto'),
        ),
    ]
